version: '3.8'
services:
  db:
    image: postgres:15
    container_name: mundial-db
    environment:
      POSTGRES_DB: mundialhub
      POSTGRES_USER: dsuar
      POSTGRES_PASSWORD: David210310
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: mundial-app
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mundialhub
      SPRING_DATASOURCE_USERNAME: dsuar
      SPRING_DATASOURCE_PASSWORD: David210310