input {
  file {
    # La ruta donde Logstash buscará el archivo JSON que crea tu Spring Boot
    path => "/usr/share/logstash/logs/mundial-hub*.json"
    start_position => "beginning"
    codec => "json"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "mundial-hub-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}